// <auto-generated />
namespace ScrumProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class sixth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sixth));
        
        string IMigrationMetadata.Id
        {
            get { return "201304091139091_sixth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
