// <auto-generated />
namespace ScrumProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class third : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(third));
        
        string IMigrationMetadata.Id
        {
            get { return "201304081658326_third"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
