// <auto-generated />
namespace ScrumProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fourth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fourth));
        
        string IMigrationMetadata.Id
        {
            get { return "201304090923576_fourth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
